### ISSUE TITLE
Polyline path wasn't drawn

### ISSUE THREAD

**Issue by shaon2016** [tintinscorpion/Dual-color-Polyline-Animation#5]
I have passed decoded path to your Class. But no path or no animation was showing. 

But in general path is drawn by this below code.

`mMap.addPolyline(
                PolylineOptions()
                    .addAll(decodedPath)
            )`

**Comment by saneera** [comment]
***Hi

Thanks for you library, I need to ask favour from you can you able to share the Android UI which you have shown in the readme doc because I m not good at developing android UI applications so if you can share code with me that would be good help for me (Specially origin and destination picker and label on origin and destination )

*** Thanks

**Comment by ArjunBhilare** [comment]
Same for me

**Comment by tintinscorpion** [comment]
@shaon2016 Its fixed now in the latest version 1.1.. Hopefully you can test and provide feedback,

**Comment by lUjek-Sh** [comment]
Since the bug was only when 
minifyEnabled true
shrinkResources true
I will clarify how I solved this.
I added the library to the exception in the proguard-rules.pro file
